app/controllers/application_controller.rb
app/controllers/meetings_controller.rb
app/controllers/users_controller.rb
app/models/meeting.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/meetings/new.html.erb
app/views/meetings/show.html.erb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb
config/routes.rb
db/migrate/20211213125446_add_first_name_last_name_to_users.rb
db/migrate/20211213130700_create_meetings.rb
db/schema.rb
test/controllers/meetings_controller_test.rb
test/controllers/users_controller_test.rb
test/models/meeting_test.rb

Created User and Meetings models.
Created Sign-up and Login-Page
Created Dashboard
Created "Create Meeting" Page
Created "View Meeting" Page
Tests: 
Created user instance via sign-up
Created meeting instance via "create new meeting" page.

Create initial models

---

Gemfile
app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/javascript/plugins/flatpickr.js
app/models/meeting.rb
app/views/meetings/new.html.erb
config/initializers/devise.rb
package.json
yarn.lock

Added datepicker to create new meetings form. 
Test:
Created new meeting with correct start_date /end_date class and value.

Added date pickers to create new meeting form

---

Gemfile.lock
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/components/navbar.js
app/javascript/packs/application.js
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

Navbar updated with both login and sign up button
Navbar transitions to white colour when scroll down the pages

Navbar updated

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/components/_index.scss
app/controllers/meetings_controller.rb
app/models/meeting.rb
app/views/meetings/new.html.erb
app/views/meetings/upcoming.html.erb
app/views/simple_calendar/_calendar.html.erb
app/views/simple_calendar/_month_calendar.html.erb
app/views/simple_calendar/_week_calendar.html.erb
app/views/users/show.html.erb

Created upcoming meetings page.
Test: 
Step 1: Create new meeting using the form.
Step 2: Used rails console to find created meeting
Step 3: Change found meeting's status from PENDING to ACCEPTED. 
Step 4: Save meeting
Step 5: Meeting should appear in upcoming meetings page

Added upcoming events and improved create new meetings

---

Gemfile.lock

resolve conflict in gemfile.lock

---

config/initializers/devise.rb

added scope to device.rb

---

app/controllers/users/omniauth_callbacks_controller.rb
app/models/user.rb
config/initializers/devise.rb

added refresh logic for user

---

app/assets/stylesheets/components/_calendar.scss
app/controllers/meetings_controller.rb
app/models/meeting.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/meetings/send_invite.html.erb
app/views/meetings/show.html.erb
app/views/meetings/upcoming.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_navbar_index.html.erb
config/application.rb
config/routes.rb
db/migrate/20211221051444_add_image_to_users.rb
db/schema.rb

Added new view for external invite for email submission
Fixed timezone issues for meeting model (UTC TO SGT)

Add external invite

---

app/assets/stylesheets/components/_calendar.scss
app/controllers/meetings_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/tooltip_controller.js
app/javascript/packs/application.js
app/models/meeting.rb
app/models/user.rb
app/views/meetings/send_invite.html.erb
app/views/meetings/show.html.erb
app/views/meetings/upcoming.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_navbar_index.html.erb
config/application.rb
config/routes.rb
db/migrate/20211221051444_add_image_to_users.rb
db/schema.rb
package.json
yarn.lock

added tooltips to events in simple calendar, tooltip content to be updated accordingly

Add tooltips

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_signup.scss
app/assets/stylesheets/users/_show.scss
app/views/devise/registrations/new.html.erb

still need to work on the resizing of the form.

inserted background and tweaked design of sign up form

---

app/assets/stylesheets/pages/_signup.scss
app/views/devise/registrations/new.html.erb

edited signup page to follow login page design

---

app/controllers/meetings_controller.rb
app/models/choice.rb
app/models/meeting.rb
app/views/meetings/new.html.erb
db/migrate/20211229111655_create_choices.rb
db/schema.rb
test/models/choice_test.rb

Barebones function of adding choices to meeting model.
Datetime not included as there is a conflict due to the naming of the attributes in the form("named attributes").

Add choice to meetings

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_meeting_confirmation.scss
app/assets/stylesheets/users/_show.scss
app/views/meetings/meeting_confirmation.html.erb
app/views/simple_calendar/_month_calendar.html.erb

edited thank you page and cleaned up some frontend pages

---

app/controllers/meetings_controller.rb
app/javascript/plugins/flatpickr.js
app/views/meetings/new.html.erb

Added date time to choices using the original way. 
We will need to add named attributes in the future.

added datetime to choices

---

app/views/meetings/new.html.erb

Added forms to be side by side

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_invite.scss
app/views/meetings/new.html.erb
app/views/meetings/send_invite.html.erb

styled invite meeting page & edited some from end

---

app/assets/stylesheets/components/_card.scss
app/views/shared/_navbar.html.erb
app/views/shared/_navbar_index.html.erb

updated the navbar dropdown and active link

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_calendar.scss
app/views/meetings/upcoming.html.erb
app/views/simple_calendar/_month_calendar.html.erb

edited the buttons, added box shadow and media queries to the page.

styled the calendar

---

app/helpers/application_helper.rb
app/javascript/plugins/init_add_fields.js
app/javascript/plugins/init_remove_fields.js
app/views/meetings/_choice_fields.html.erb
app/views/meetings/new.html.erb

Meetings starts with 1 choice by default.
Able to add up to 3 choices.
Able to remove choices.
Test for creation of choice instances:

Improve meeting choices

---

app/assets/stylesheets/components/_choice.scss
app/assets/stylesheets/components/_index.scss
app/controllers/meetings_controller.rb
app/javascript/controllers/choice_controller.js
app/views/meetings/_choice_fields.html.erb
app/views/meetings/_choice_selection.html.erb
app/views/meetings/send_invite.html.erb

Added selection of choices to send invite page
Submit button enabled on selection of choice and selected choice highlighted
Also updated meeting controller CREATE action when there is only 1 choice.

Select choice

---

app/javascript/plugins/init_add_fields.js
app/views/meetings/send_invite.html.erb

Added logic for meeting invite page if only one choice is chosen.
**1 Choice is chosen**
Test that meeting instance is updated with choice:
**More than 1 Choice is chosen**
Test that meeting instance is updated with _selected_ choice:

One choice chosen

---

app/models/meeting.rb
app/views/meetings/new.html.erb

Removed the original meeting fields. Only choice fields can be seen. 
Test for one choice selected:
Test for more than one choice selected:

new meeting page only shows choices

---

app/controllers/meetings_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_copy_to_clipboard.js
app/views/meetings/copy_invite.html.erb
config/routes.rb

Added page to copy to clipboard for user

added copy invite page to

---

app/assets/stylesheets/pages/_invite.scss
app/assets/stylesheets/pages/_meeting_confirmation.scss
app/views/meetings/meeting_confirmation.html.erb
app/views/meetings/send_invite.html.erb

adjusted the margin and padding of the box to look nicer in mobile mode.

made send invite and confirmation page responsive

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_calendar.scss
app/views/meetings/upcoming.html.erb
app/views/simple_calendar/_month_calendar.html.erb

added css for upcoming calendar

---

app/assets/stylesheets/components/_choice.scss
app/assets/stylesheets/pages/_invite.scss
app/views/meetings/_choice_selection.html.erb
app/views/meetings/send_invite.html.erb

Edit send invite css

---

app/assets/stylesheets/components/_choice.scss
app/javascript/plugins/init_add_fields.js
app/javascript/plugins/init_remove_fields.js
app/views/meetings/_choice_fields.html.erb
app/views/meetings/new.html.erb

Added css to meeting choices

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_customflatpickr.scss
app/assets/stylesheets/components/_index.scss

added front end for new meetings

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/components/_choice.scss
app/assets/stylesheets/meetings/_index.scss
app/assets/stylesheets/meetings/_send_invite.scss
app/models/meeting.rb
app/views/meetings/_choice_fields.html.erb
app/views/meetings/new.html.erb
app/views/meetings/send_invite.html.erb
app/views/meetings/upcoming.html.erb
app/views/simple_calendar/_month_calendar.html.erb

changed css as per Ann's recommendation

edited css as per recommendations

---

app/models/user.rb

For new connections made,
For completed coffee chats,
For recurring chats,

created user class methods for dashboard engagement column

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_choice.scss
app/assets/stylesheets/components/_customflatpickr.scss
app/views/meetings/new.html.erb

Meetings front end

---

app/assets/stylesheets/components/_button.scss
app/views/meetings/new.html.erb
app/views/users/show.html.erb

Populate engagements

---

app/views/meetings/send_invite.html.erb

front end for send invite page

---

app/assets/stylesheets/meetings/_index.scss
app/assets/stylesheets/meetings/_upcoming.scss
app/javascript/controllers/copyclipboard_controller.js
app/views/meetings/_copy_to_clipboard.erb
app/views/meetings/upcoming.html.erb

Improve meetings front end ii

---

app/assets/stylesheets/meetings/_copy_invite.scss
app/assets/stylesheets/meetings/_index.scss
app/views/meetings/copy_invite.html.erb
app/views/meetings/upcoming.html.erb

Front end touch ups

---

app/views/users/show.html.erb

aligned update user button to center

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_column.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/users/_show.scss
app/views/pages/home.html.erb
app/views/shared/_navbar_index.html.erb

Fixed frontend
